base_url: https://akshayshah.org
author: Akshay Shah
description: "Code, cooking, and caffeine."
css: style.css

pages:
  # Hidden from homepage
  - markdown: 404.md
    description: "404 Not Found"
    hidden: true
  - markdown: license.md
    description: "The license for all content on this site."
    hide_license: true
    hidden: true
  - markdown: colophon.md
    description: "I'm Akshay Shah, and you've landed on my little patch of the web - mazel tov!"
    hidden: true
    created: 2012-08-01
    updated: 2022-05-22

  # Posts
  - markdown: building-a-blog.md
    description: "Building a blog with Hakyll and Bootstrap."
    created: 2012-08-01
    updated: 2020-05-01
  - markdown: zero-to-code-monkey.md
    description: "Lessons from my first year as a professional programmer."
    created: 2012-09-01
  - markdown: audible-literacy-filter.md
    description: "Screening job applicants with a simple grammatical test."
    created: 2012-10-01
    updated: 2020-05-01
  - markdown: language-use-on-github.md
    description: "Using the GitHub Archive to find programming language correlations."
    created: 2013-02-01
    updated: 2020-06-01
  - markdown: soft-deletion-in-django.md
    description: "A soft-deletion approach for Django applications that preserves uniqueness constraints."
    created: 2013-05-01
    updated: 2013-08-01
  - markdown: license-your-code.md
    description: "A brief orientation to software licensing."
    created: 2013-08-01
  - markdown: testing-django-fields.md
    description: "Minimize boilerplate when testing custom Django model fields."
    created: 2013-08-01
  - markdown: podcasts-for-developers.md
    description: "A selection of well-produced podcasts for programmers."
    created: 2015-05-01
  - markdown: decade-of-cap.md
    description: "Slides and resources from a talk on Eric Brewer's CAP theorem."
    created: 2016-03-01
  - markdown: getting-started-with-go.md
    description: "An opinionated plan to learn Go in a hurry."
    created: 2018-05-01
  - markdown: grit.md
    description: "Reading notes from Angela Duckworth's Grit."
    created: 2019-06-01
    updated: 2022-05-01
  - markdown: lazy-loading-data-with-swiftui-and-combine.md
    description: "An approach to automatically fetch resources when SwiftUI views render."
    created: 2020-01-01
    updated: 2020-05-01
  - markdown: automating-gmail-with-appsscript.md
    description: "Smarter email automation with Google AppsScript."
    created: 2020-06-01
  - markdown: sourdough.md
    description: "Reading notes from Robin Sloan's Sourdough."
    created: 2020-08-01
  - title: "Connect: A Better gRPC"
    link: https://buf.build/blog/connect-a-better-grpc/
    via: "on the Buf blog"
    created: 2022-06-01
  - markdown: go-time-protobuf-grpc.md
    description: "I was interviewed on the Go Time podcast about Protocol Buffers and gRPC."
    created: 2022-11-17

  # Recipes
  - markdown: recipes/garam-masala.md
    description: "A recipe for garam masala."
    created: 2020-01-01
  - markdown: recipes/bakers-percentages.md
    description: "An explanation of baker's percentages."
    created: 2020-03-01
    updated: 2020-05-01
  - markdown: recipes/sourdough-starter.md
    description: "A recipe for homemade sourdough starter."
    created: 2020-03-01
    updated: 2020-05-01
  - markdown: recipes/focaccia.md
    description: "Recipes for quick and sourdough focaccia."
    created: 2020-03-01
    updated: 2020-05-01
  - markdown: recipes/chicken-kebabs.md
    description: "A recipes for Indian-inspired chicken kebabs."
    created: 2020-05-01
  - markdown: recipes/methi-murgh.md
    description: "My mother-in-law's recipe for a methi-flavored chicken curry."
    created: 2020-05-01
    updated: 2020-06-01
  - markdown: recipes/waffles.md
    description: "Recipes for quick and sourdough waffles."
    created: 2020-05-01
  - markdown: recipes/hokkaido-milk-bread.md
    description: "A recipe for a long-lasting, Japanese-style enriched sandwich bread."
    created: 2020-05-01
  - markdown: recipes/pizza.md
    title: "A pizza recipe honed over two decades."
    created: 2020-05-01
    updated: 2020-06-01
  - markdown: recipes/coriander-mint-chutney.md
    description: "My mother-in-law's coriander chutney recipe."
    created: 2020-06-01
  - markdown: recipes/methi-dal.md
    description: "My mother-in-law's recipe for methi dal."
    created: 2020-06-01
  - markdown: recipes/pancakes.md
    description: "Recipes for buttermilk and lemon-ricotta pancakes."
    created: 2020-01-15
